#!/bin/sh

if npm run doc >/dev/null 2>&1
then
	if git status --porcelain | grep ' M README.md' >/dev/null 2>&1
	then
		echo 'You have unstaged README updates that need to be committed'
		git status -s
		exit 1
	elif npm run check-deps >/dev/null 2>&1
	then
		echo 'You have outdated dependencies'
		exit 1
	fi
else
	exit 1
fi

exit 0
